#!/bin/bash

python main.py \
    --mode train \
    --exper-name m2max_fastUAR70_vitb32_wrs_logitadj_tau05_mi07_dc12_colab \
    --gpu 0 \
    --epochs 50 \
    --batch-size 8 \
    --lr 0.0003 \
    --lr-image-encoder 1e-06 \
    --lr-prompt-learner 0.001 \
    --lr-adapter 1e-4 \
    --weight-decay 0.0001 \
    --momentum 0.9 \
    --milestones 20 35 \
    --gamma 0.1 \
    --temporal-layers 1 \
    --num-segments 16 \
    --duration 1 \
    --image-size 224 \
    --seed 42 \
    --print-freq 10 \
    --root-dir /content/drive/MyDrive/khoaluan/Dataset/RAER \
    --train-annotation /content/drive/MyDrive/khoaluan/Dataset/annotation/train_80.txt \
    --test-annotation /content/drive/MyDrive/khoaluan/Dataset/annotation/val_20.txt \
    --clip-path ViT-B/32 \
    --bounding-box-face /content/drive/MyDrive/khoaluan/Dataset/annotation/bounding_box/face.json \
    --bounding-box-body /content/drive/MyDrive/khoaluan/Dataset/annotation/bounding_box/body.json \
    --text-type class_descriptor \
    --contexts-number 12 \
    --class-token-position end \
    --class-specific-contexts True \
    --load_and_tune_prompt_learner True \
    --mi-loss-weight 0.7 \
    --dc-loss-weight 1.2 \
    --slerp-weight 0.5 \
    --logit-adj \
    --logit-adj-tau 0.5 \
    --temperature 0.07
